apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceresourcereports.zgg2001.github.com
spec:
  group: zgg2001.github.com
  names:
    kind: NamespaceResourceReport
    listKind: NamespaceResourceReportList
    plural: namespaceresourcereports
    singular: namespaceresourcereport
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            description: Spec defines the behavior of a namespace resource report
            properties:
              namespace:
                type: string
            required:
            - namespace
            type: object
          status:
            description: Spec defines the behavior of a namespace resource report
            properties:
              cpuUsed:
                type: string
              memUsed:
                type: string
            type: object
        required:
        - metadata
        - spec