apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      hostNetwork: true
      containers:
      - name: reporter-container
        image: zgg2001/reporter:1.0